name: iOS-CI

on:
  push:
    branches: 'feature/iOS/*'
  pull_request:
    branches: 'develop'
    types: [labeled, opened, synchronize, reopened]

jobs:
  tuist-test:
    if: contains(github.event.pull_request.labels.*.name, '📱 iOS')
    runs-on: macos-13
    env:
      working-directory: ./iOS

    steps:
      - name: Xcode Version Settings
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "15.0.1"

      - name: Code Checkout
      - uses: actions/checkout@v3

      - name: Install Tuist
        run: brew install tuist
        working-directory: ${{env.working-directory}}

      - name: Print Tuist Version
        run: tuist version
        working-directory: ${{env.working-directory}}

      - name: Run Tuist Test
        run: make test
        working-directory: ${{env.working-directory}}
